---
name: ((deployment_name))

releases:
- name: "concourse"
  version: "7.0.0"
  url: "https://bosh.io/d/github.com/concourse/concourse-bosh-release?v=7.0.0"
  sha1: "90bc416cfd6c9bd03447b77accb3d9f185d69281"
- name: "postgres"
  version: "43"
  url: "https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=43"
  sha1: "e44bbe8f8a7cdde1cda67b202e399a239d104db6"
- name: "bpm"
  version: "1.1.9"
  url: "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.9"
  sha1: "dcf0582d838a73de29da273552ae79ac3098ee8b"

instance_groups:
- name: concourse
  instances: 1
  azs: [z1]
  networks:
  - name: ((network_name))
  persistent_disk: 10240
  vm_type: ((vm_type))
  stemcell: xenial
  jobs:
  - release: bpm
    name: bpm

  - release: concourse
    name: web
    properties:
      log_level: debug

      postgresql:
        database: atc
        role:
          name: atc
          password: ((postgres_password))

      main_team:
        auth:
          local:
            users: [test]

      add_local_users:
      - test:test

      token_signing_key: ((token_signing_key))

      worker_gateway:
        host_key: ((tsa_host_key))
        authorized_keys: [((worker_key.public_key))]

  - release: concourse
    name: worker
    properties:
      worker_gateway:
        worker_key: ((worker_key))

  - release: postgres
    name: postgres
    properties:
      databases:
        port: 5432
        databases:
        - name: atc
        roles:
        - name: atc
          password: ((postgres_password))

variables:
- name: postgres_password
  type: password
- name: token_signing_key
  type: rsa
- name: tsa_host_key
  type: ssh
- name: worker_key
  type: ssh

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000